# Docker Compose override for development environment
# This file is automatically loaded by docker-compose when present
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  # Pandora Box PWA in development mode
  pandora-box:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - HOT_RELOAD=true
    volumes:
      # Mount source code for hot reload
      - ./server/src:/app/server/src
      - ./client/src:/app/client/src
      - ./server/package.json:/app/server/package.json
      - ./client/package.json:/app/client/package.json
    ports:
      - "3001:3001"  # API server
      - "5173:5173"  # Vite dev server
      - "9229:9229"  # Node.js debugger
    command: npm run dev
    depends_on: []  # Remove dependencies for faster startup in dev

  # Development services with simplified configuration
  jackett:
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./dev-data/jackett:/config
      - ./downloads:/downloads

  qbittorrent:
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ./dev-data/qbittorrent:/config
      - ./downloads:/downloads

  cloudcmd:
    ports:
      - "8000:8000"
    volumes:
      - ./media:/files/media
      - ./downloads:/files/downloads

  portainer:
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dev-data/portainer:/data

  jellyfin:
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./dev-data/jellyfin/config:/config
      - ./dev-data/jellyfin/cache:/cache
      - ./media:/media:ro

volumes:
  # Use local directories for development
  pandora-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev-data/pandora
  
  pandora-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev-data/logs

networks:
  pandora-network:
    driver: bridge
  media-network:
    driver: bridge